Update DrvGen.py
Fix:
```
File "/home/runner/work/kernel_action_mt6768/kernel_action_mt6768/kernel_workspace/android-kernel/out/../tools/dct/DrvGen.py", line 48
    print '''
    ^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```